name: Broken Links Checker
on:
  push:
    branches: ["main"]

  workflow_dispatch:
env:
  WEBSITE_URL: "https://bananachad.github.io/TheOdinProject/"
  ISSUE_TEMPLATE: ".github/workflows/check-broken-links.md"
concurrency:
  group: "pages"
  cancel-in-progress: false
permissions:
  contents: read
  issues: write

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Run Broken Links Checker
        run: npx broken-link-checker $WEBSITE_URL --ordered --recursive --user-agent "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0" --exclude linkedin --exclude "udemy" --exclude "ude.my" --exclude "eia.gov" --exclude "backpack.tf" --exclude hlsw --exclude dell --exclude supermicro --exclude mysql --exclude glassdoor --exclude "https://bananachad.github.io/TheOdinProject/odin-recipes/recipes/" --exclude flaticon

      - uses: actions/checkout@v4.1.7
        if: failure()

      - uses: JasonEtco/create-an-issue@v2.9.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: ${{ env.ISSUE_TEMPLATE }}
        if: failure()
